In [255]:
import pandas as pd
import datetime
import numpy as np
import pickle

In [256]:
cgmdata = pd.read_csv('CGMData.csv', sep=',', low_memory = False)
insulindata = pd.read_csv('InsulinData.csv', sep=',', low_memory = False)
# display(cgmdata)
# display(insulindata)

/Users/kinlay/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/kinlay/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (13,43) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [257]:
# Extract data for meal time
mealTimes = insulindata.loc[insulindata['BWZ Carb Input (grams)'] > 0][['Index', 'Date', 'Time', 'BWZ Carb Input (grams)']]

# Add a new column named "dataTime"
mealTimes['dateTime'] = pd.to_datetime(mealTimes['Date'] + ' ' + mealTimes['Time'])
cgmdata['dateTime'] = pd.to_datetime(cgmdata['Date'] + ' ' + cgmdata['Time'])

In [258]:
# Compare the dateTime to identify how long have one eaten the previous meal
mealTimes['diff'] = mealTimes['dateTime'].diff(periods=-1)
mealTimes['shiftDownRow'] = mealTimes['diff'].shift(1)
mealTimes

,Index,Date,Time,BWZ Carb Input (grams),dateTime,diff,shiftDownRow
48,48,2/12/2018,9:15:45,34.0,2018-02-12 09:15:45,06:44:50,NaT
129,129,2/12/2018,2:30:55,15.0,2018-02-12 02:30:55,05:57:37,06:44:50
188,188,2/11/2018,20:33:18,71.0,2018-02-11 20:33:18,02:18:41,05:57:37
207,207,2/11/2018,18:14:37,8.0,2018-02-11 18:14:37,01:47:33,02:18:41
222,222,2/11/2018,16:27:04,40.0,2018-02-11 16:27:04,00:52:38,01:47:33
...,...,...,...,...,...,...,...
41265,21970,7/26/2017,11:24:52,20.0,2017-07-26 11:24:52,01:57:36,01:23:49
41274,21979,7/26/2017,9:27:16,72.0,2017-07-26 09:27:16,14:55:36,01:57:36
41347,22052,7/25/2017,18:31:40,115.0,2017-07-25 18:31:40,07:51:54,14:55:36
41393,22098,7/25/2017,10:39:46,58.0,2017-07-25 10:39:46,00:18:27,07:51:54
41401,22106,7/25/2017,10:21:19,91.0,2017-07-25 10:21:19,NaT,00:18:27

In [259]:
# Using the previous meal time, filter out any meals eaten before the threshold (2 hours)
mealTimes = mealTimes.loc[(mealTimes['shiftDownRow'] > datetime.timedelta (minutes = 120)) | (pd.isnull(mealTimes['shiftDownRow']))]
# display("Before:", mealTimes)
mealTimes = mealTimes[['Date', 'Time', 'BWZ Carb Input (grams)', 'dateTime']]
display("After:", mealTimes)

'After:'

            Date      Time  BWZ Carb Input (grams)            dateTime
48     2/12/2018   9:15:45                    34.0 2018-02-12 09:15:45
129    2/12/2018   2:30:55                    15.0 2018-02-12 02:30:55
188    2/11/2018  20:33:18                    71.0 2018-02-11 20:33:18
207    2/11/2018  18:14:37                     8.0 2018-02-11 18:14:37
261    2/11/2018  12:43:23                    27.0 2018-02-11 12:43:23
...          ...       ...                     ...                 ...
41172  7/27/2017   5:45:51                    24.0 2017-07-27 05:45:51
41214  7/26/2017  19:15:06                    60.0 2017-07-26 19:15:06
41261  7/26/2017  12:48:41                    63.0 2017-07-26 12:48:41
41347  7/25/2017  18:31:40                   115.0 2017-07-25 18:31:40
41393  7/25/2017  10:39:46                    58.0 2017-07-25 10:39:46

[604 rows x 4 columns]

In [260]:
# Create a new dataframe. Using the meal time data from insulindata file and filter out the relevant time. Add those rows into the new dataframe
cgmdata_withMeal = pd.DataFrame()
for i in range(len(mealTimes)) : 
    preMealTime = mealTimes['dateTime'].iloc[i] - datetime.timedelta(minutes = 30)
    endMealTime = mealTimes['dateTime'].iloc[i] + datetime.timedelta(minutes = 120)
    filteredcgmdata = cgmdata.loc[(cgmdata['dateTime'] >= preMealTime) & (cgmdata['dateTime'] < endMealTime )]
#     display(filteredcgmdata)
    arr = []
    for j in range(len(filteredcgmdata)) :
        arr.append(filteredcgmdata['Sensor Glucose (mg/dL)'].iloc[j])
    cgmdata_withMeal = cgmdata_withMeal.append(pd.Series(arr), ignore_index=True)

cgmdata_withMeal = cgmdata_withMeal.dropna()
cgmdata_withMeal

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,150.0,162.0,174.0,180.0,178.0,184.0,185.0,194.0,193.0,186.0,...,159.0,160.0,158.0,158.0,153.0,154.0,151.0,150.0,149.0,150.0
2,177.0,194.0,200.0,201.0,189.0,162.0,166.0,173.0,176.0,169.0,...,132.0,120.0,127.0,129.0,132.0,123.0,104.0,100.0,107.0,106.0
4,208.0,215.0,212.0,206.0,203.0,196.0,190.0,180.0,184.0,180.0,...,200.0,201.0,211.0,215.0,217.0,216.0,221.0,221.0,219.0,209.0
5,202.0,197.0,191.0,185.0,197.0,206.0,209.0,207.0,174.0,168.0,...,141.0,135.0,133.0,126.0,110.0,104.0,74.0,62.0,58.0,57.0
6,106.0,114.0,136.0,155.0,163.0,169.0,162.0,158.0,153.0,146.0,...,133.0,126.0,100.0,82.0,70.0,65.0,60.0,59.0,59.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,200.0,198.0,191.0,183.0,175.0,172.0,157.0,147.0,140.0,132.0,...,77.0,70.0,58.0,55.0,57.0,57.0,53.0,46.0,40.0,40.0
598,152.0,153.0,165.0,173.0,177.0,179.0,183.0,189.0,196.0,200.0,...,130.0,123.0,122.0,125.0,124.0,129.0,133.0,137.0,141.0,145.0
599,209.0,210.0,209.0,210.0,210.0,213.0,216.0,212.0,213.0,210.0,...,183.0,188.0,194.0,201.0,201.0,199.0,200.0,204.0,210.0,212.0
600,81.0,77.0,74.0,67.0,70.0,72.0,74.0,75.0,71.0,67.0,...,112.0,100.0,87.0,83.0,71.0,60.0,40.0,40.0,40.0,40.0
601,278.0,283.0,284.0,274.0,267.0,267.0,269.0,274.0,277.0,270.0,...,220.0,231.0,241.0,248.0,255.0,259.0,268.0,281.0,292.0,304.0

In [261]:
flip_insulindata = insulindata.loc[::-1,:]
flip_insulindata['dateTime'] = pd.to_datetime(flip_insulindata['Date'] + ' ' + flip_insulindata['Time'])
reverse_insulindata = flip_insulindata[['Date', 'Time', 'BWZ Carb Input (grams)', 'dateTime']]
reverse_mealTimes = mealTimes.loc[::-1,:]
# display(reverse_insulindata)
# display(reverse_mealTimes)

/Users/kinlay/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [262]:
# Get the no meal start time into an array
no_meal_time = []
for i in range(len(reverse_mealTimes)) : 
    startTime = reverse_mealTimes['dateTime'].iloc[i] + datetime.timedelta(minutes = 120)
    endTime = startTime + datetime.timedelta(minutes = 120)
    fullDataEndTime = reverse_insulindata['dateTime'].iloc[-1]
    no_meal_continue = True
    while (no_meal_continue == True) :
        tempRange = reverse_insulindata.loc[(reverse_insulindata['dateTime'] >= startTime) & (reverse_insulindata['dateTime'] < endTime) & (reverse_insulindata['BWZ Carb Input (grams)'] > 0)]
        if (len(tempRange) > 0) :
            no_meal_continue = False
        else :
            no_meal_time.append(startTime)
        startTime = startTime + datetime.timedelta(minutes = 120)
        endTime = endTime + datetime.timedelta(minutes = 120)
        if (startTime > fullDataEndTime) :
            no_meal_continue = False

# display(no_meal_time)

In [263]:
# Use the no meal start time and apply to the cgmdata file
reverse_cgmdata = cgmdata.loc[::-1,:]
cgmdata_noMeal = pd.DataFrame()
for i in no_meal_time:
    noMealStartTime = i
    noMealEndTime = i + datetime.timedelta(minutes = 120)
    filteredcgmdata = reverse_cgmdata.loc[(reverse_cgmdata['dateTime'] >= noMealStartTime) & (reverse_cgmdata['dateTime'] < noMealEndTime)]
    arr = []
    for j in range(len(filteredcgmdata)):
        arr.append(filteredcgmdata['Sensor Glucose (mg/dL)'].iloc[j])
    if (len(arr) > 24):
        continue
    cgmdata_noMeal = cgmdata_noMeal.append(pd.Series(arr), ignore_index=True)
    
cgmdata_noMeal

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,312.0,316.0,324.0,319.0,315.0,314.0,316.0,314.0,310.0,298.0,...,289.0,294.0,290.0,278.0,251.0,229.0,208.0,198.0,186.0,174.0
1,160.0,145.0,134.0,129.0,120.0,113.0,109.0,106.0,100.0,95.0,...,77.0,73.0,70.0,65.0,62.0,59.0,58.0,63.0,71.0,81.0
2,189.0,182.0,175.0,166.0,146.0,138.0,129.0,123.0,118.0,114.0,...,82.0,77.0,71.0,66.0,63.0,65.0,66.0,64.0,62.0,61.0
3,64.0,67.0,69.0,67.0,63.0,60.0,55.0,53.0,53.0,54.0,...,65.0,64.0,64.0,65.0,65.0,64.0,64.0,67.0,72.0,78.0
4,86.0,89.0,90.0,89.0,89.0,90.0,91.0,90.0,87.0,83.0,...,95.0,95.0,92.0,92.0,93.0,91.0,89.0,92.0,99.0,106.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,161.0,153.0,158.0,165.0,164.0,166.0,170.0,175.0,182.0,205.0,...,250.0,245.0,250.0,259.0,262.0,260.0,279.0,289.0,288.0,287.0
1460,79.0,69.0,58.0,49.0,73.0,83.0,90.0,87.0,82.0,73.0,...,131.0,NaN,101.0,103.0,103.0,106.0,110.0,115.0,120.0,121.0
1461,125.0,127.0,127.0,131.0,130.0,131.0,140.0,169.0,168.0,165.0,...,137.0,143.0,145.0,147.0,147.0,149.0,150.0,151.0,152.0,150.0
1462,151.0,148.0,146.0,140.0,157.0,159.0,NaN,148.0,134.0,130.0,...,140.0,137.0,130.0,128.0,127.0,126.0,124.0,NaN,NaN,NaN
1463,122.0,118.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [264]:
cgmdata_noMeal = cgmdata_noMeal.dropna()
cgmdata_noMeal

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,312.0,316.0,324.0,319.0,315.0,314.0,316.0,314.0,310.0,298.0,...,289.0,294.0,290.0,278.0,251.0,229.0,208.0,198.0,186.0,174.0
1,160.0,145.0,134.0,129.0,120.0,113.0,109.0,106.0,100.0,95.0,...,77.0,73.0,70.0,65.0,62.0,59.0,58.0,63.0,71.0,81.0
2,189.0,182.0,175.0,166.0,146.0,138.0,129.0,123.0,118.0,114.0,...,82.0,77.0,71.0,66.0,63.0,65.0,66.0,64.0,62.0,61.0
3,64.0,67.0,69.0,67.0,63.0,60.0,55.0,53.0,53.0,54.0,...,65.0,64.0,64.0,65.0,65.0,64.0,64.0,67.0,72.0,78.0
4,86.0,89.0,90.0,89.0,89.0,90.0,91.0,90.0,87.0,83.0,...,95.0,95.0,92.0,92.0,93.0,91.0,89.0,92.0,99.0,106.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,96.0,95.0,94.0,92.0,89.0,87.0,87.0,86.0,84.0,81.0,...,62.0,67.0,71.0,75.0,75.0,79.0,95.0,126.0,131.0,140.0
1457,144.0,150.0,141.0,126.0,116.0,107.0,111.0,114.0,115.0,113.0,...,80.0,86.0,92.0,90.0,84.0,75.0,70.0,72.0,69.0,69.0
1458,66.0,63.0,67.0,70.0,70.0,69.0,65.0,62.0,63.0,63.0,...,61.0,60.0,60.0,61.0,60.0,57.0,58.0,57.0,58.0,62.0
1459,161.0,153.0,158.0,165.0,164.0,166.0,170.0,175.0,182.0,205.0,...,250.0,245.0,250.0,259.0,262.0,260.0,279.0,289.0,288.0,287.0
1461,125.0,127.0,127.0,131.0,130.0,131.0,140.0,169.0,168.0,165.0,...,137.0,143.0,145.0,147.0,147.0,149.0,150.0,151.0,152.0,150.0

In [265]:
cgmdata_withMeal_feature_extraction = cgmdata_withMeal
cgmdata_withMeal_feature_extraction['max_value'] = cgmdata_withMeal_feature_extraction.max(axis=1)
cgmdata_withMeal_feature_extraction['min_value'] = cgmdata_withMeal_feature_extraction.min(axis=1)
cgmdata_withMeal_feature_extraction['dG_n'] = cgmdata_withMeal_feature_extraction['max_value'] - cgmdata_withMeal_feature_extraction['min_value']
# cgmdata_withMeal_feature_extraction

In [266]:
# cgmdata_withMeal.to_csv('Results.csv', header=False, index=False)

In [267]:
# Remove the last 6 columns of meal data
# Reverse the order of data from left to right
# The reason for the reverse because the meal data is extracted with data that are newest on the top and oldest on the bottom, and therefore, "cgmdata_withMeal" list newest data on the left and oldest list on the right
# The no meal data, however, extracts from data that are oldest on the top and newest on the bottom. So "cgmdata_noMeal" list data oldest from the left and newest on the right/
# By removing the data on the right, we are removing the oldest data and keep data from meal time to 2 hr plus.
# We reverse "cgmdata_withMeal" to be consistent with "cgmdata_noMeal" that older data on the left.
display(cgmdata_withMeal)
cgmdata_withMeal = cgmdata_withMeal.iloc[:,0:24]
cgmdata_withMeal = cgmdata_withMeal.iloc[:, ::-1]
cgmdata_withMeal.columns = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
cgmdata_withMeal['label'] = 1
cgmdata_noMeal['label'] = 0


display(cgmdata_withMeal)
display(cgmdata_noMeal)

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,max_value,min_value,dG_n
0,150.0,162.0,174.0,180.0,178.0,184.0,185.0,194.0,193.0,186.0,...,158.0,153.0,154.0,151.0,150.0,149.0,150.0,194.0,149.0,45.0
2,177.0,194.0,200.0,201.0,189.0,162.0,166.0,173.0,176.0,169.0,...,129.0,132.0,123.0,104.0,100.0,107.0,106.0,201.0,100.0,101.0
4,208.0,215.0,212.0,206.0,203.0,196.0,190.0,180.0,184.0,180.0,...,215.0,217.0,216.0,221.0,221.0,219.0,209.0,221.0,177.0,44.0
5,202.0,197.0,191.0,185.0,197.0,206.0,209.0,207.0,174.0,168.0,...,126.0,110.0,104.0,74.0,62.0,58.0,57.0,209.0,57.0,152.0
6,106.0,114.0,136.0,155.0,163.0,169.0,162.0,158.0,153.0,146.0,...,82.0,70.0,65.0,60.0,59.0,59.0,61.0,169.0,59.0,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,200.0,198.0,191.0,183.0,175.0,172.0,157.0,147.0,140.0,132.0,...,55.0,57.0,57.0,53.0,46.0,40.0,40.0,200.0,40.0,160.0
598,152.0,153.0,165.0,173.0,177.0,179.0,183.0,189.0,196.0,200.0,...,125.0,124.0,129.0,133.0,137.0,141.0,145.0,213.0,122.0,91.0
599,209.0,210.0,209.0,210.0,210.0,213.0,216.0,212.0,213.0,210.0,...,201.0,201.0,199.0,200.0,204.0,210.0,212.0,216.0,168.0,48.0
600,81.0,77.0,74.0,67.0,70.0,72.0,74.0,75.0,71.0,67.0,...,83.0,71.0,60.0,40.0,40.0,40.0,40.0,132.0,40.0,92.0
601,278.0,283.0,284.0,274.0,267.0,267.0,269.0,274.0,277.0,270.0,...,248.0,255.0,259.0,268.0,281.0,292.0,304.0,304.0,220.0,84.0

/Users/kinlay/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,label
0,158.0,158.0,160.0,159.0,164.0,167.0,166.0,165.0,164.0,166.0,...,193.0,194.0,185.0,184.0,178.0,180.0,174.0,162.0,150.0,1
2,129.0,127.0,120.0,132.0,138.0,145.0,160.0,171.0,178.0,182.0,...,176.0,173.0,166.0,162.0,189.0,201.0,200.0,194.0,177.0,1
4,215.0,211.0,201.0,200.0,198.0,196.0,194.0,200.0,220.0,207.0,...,184.0,180.0,190.0,196.0,203.0,206.0,212.0,215.0,208.0,1
5,126.0,133.0,135.0,141.0,144.0,137.0,137.0,148.0,147.0,136.0,...,174.0,207.0,209.0,206.0,197.0,185.0,191.0,197.0,202.0,1
6,82.0,100.0,126.0,133.0,132.0,128.0,121.0,115.0,108.0,106.0,...,153.0,158.0,162.0,169.0,163.0,155.0,136.0,114.0,106.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,55.0,58.0,70.0,77.0,87.0,99.0,108.0,112.0,120.0,127.0,...,140.0,147.0,157.0,172.0,175.0,183.0,191.0,198.0,200.0,1
598,125.0,122.0,123.0,130.0,149.0,162.0,169.0,179.0,192.0,203.0,...,196.0,189.0,183.0,179.0,177.0,173.0,165.0,153.0,152.0,1
599,201.0,194.0,188.0,183.0,181.0,176.0,170.0,168.0,169.0,172.0,...,213.0,212.0,216.0,213.0,210.0,210.0,209.0,210.0,209.0,1
600,83.0,87.0,100.0,112.0,121.0,125.0,130.0,132.0,123.0,112.0,...,71.0,75.0,74.0,72.0,70.0,67.0,74.0,77.0,81.0,1
601,248.0,241.0,231.0,220.0,222.0,222.0,222.0,223.0,224.0,228.0,...,277.0,274.0,269.0,267.0,267.0,274.0,284.0,283.0,278.0,1

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,label
0,312.0,316.0,324.0,319.0,315.0,314.0,316.0,314.0,310.0,298.0,...,294.0,290.0,278.0,251.0,229.0,208.0,198.0,186.0,174.0,0
1,160.0,145.0,134.0,129.0,120.0,113.0,109.0,106.0,100.0,95.0,...,73.0,70.0,65.0,62.0,59.0,58.0,63.0,71.0,81.0,0
2,189.0,182.0,175.0,166.0,146.0,138.0,129.0,123.0,118.0,114.0,...,77.0,71.0,66.0,63.0,65.0,66.0,64.0,62.0,61.0,0
3,64.0,67.0,69.0,67.0,63.0,60.0,55.0,53.0,53.0,54.0,...,64.0,64.0,65.0,65.0,64.0,64.0,67.0,72.0,78.0,0
4,86.0,89.0,90.0,89.0,89.0,90.0,91.0,90.0,87.0,83.0,...,95.0,92.0,92.0,93.0,91.0,89.0,92.0,99.0,106.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,96.0,95.0,94.0,92.0,89.0,87.0,87.0,86.0,84.0,81.0,...,67.0,71.0,75.0,75.0,79.0,95.0,126.0,131.0,140.0,0
1457,144.0,150.0,141.0,126.0,116.0,107.0,111.0,114.0,115.0,113.0,...,86.0,92.0,90.0,84.0,75.0,70.0,72.0,69.0,69.0,0
1458,66.0,63.0,67.0,70.0,70.0,69.0,65.0,62.0,63.0,63.0,...,60.0,60.0,61.0,60.0,57.0,58.0,57.0,58.0,62.0,0
1459,161.0,153.0,158.0,165.0,164.0,166.0,170.0,175.0,182.0,205.0,...,245.0,250.0,259.0,262.0,260.0,279.0,289.0,288.0,287.0,0
1461,125.0,127.0,127.0,131.0,130.0,131.0,140.0,169.0,168.0,165.0,...,143.0,145.0,147.0,147.0,149.0,150.0,151.0,152.0,150.0,0

In [268]:
merged_data = pd.concat([cgmdata_withMeal, cgmdata_noMeal])
merged_data

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,label
0,158.0,158.0,160.0,159.0,164.0,167.0,166.0,165.0,164.0,166.0,...,193.0,194.0,185.0,184.0,178.0,180.0,174.0,162.0,150.0,1
2,129.0,127.0,120.0,132.0,138.0,145.0,160.0,171.0,178.0,182.0,...,176.0,173.0,166.0,162.0,189.0,201.0,200.0,194.0,177.0,1
4,215.0,211.0,201.0,200.0,198.0,196.0,194.0,200.0,220.0,207.0,...,184.0,180.0,190.0,196.0,203.0,206.0,212.0,215.0,208.0,1
5,126.0,133.0,135.0,141.0,144.0,137.0,137.0,148.0,147.0,136.0,...,174.0,207.0,209.0,206.0,197.0,185.0,191.0,197.0,202.0,1
6,82.0,100.0,126.0,133.0,132.0,128.0,121.0,115.0,108.0,106.0,...,153.0,158.0,162.0,169.0,163.0,155.0,136.0,114.0,106.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,96.0,95.0,94.0,92.0,89.0,87.0,87.0,86.0,84.0,81.0,...,67.0,71.0,75.0,75.0,79.0,95.0,126.0,131.0,140.0,0
1457,144.0,150.0,141.0,126.0,116.0,107.0,111.0,114.0,115.0,113.0,...,86.0,92.0,90.0,84.0,75.0,70.0,72.0,69.0,69.0,0
1458,66.0,63.0,67.0,70.0,70.0,69.0,65.0,62.0,63.0,63.0,...,60.0,60.0,61.0,60.0,57.0,58.0,57.0,58.0,62.0,0
1459,161.0,153.0,158.0,165.0,164.0,166.0,170.0,175.0,182.0,205.0,...,245.0,250.0,259.0,262.0,260.0,279.0,289.0,288.0,287.0,0
1461,125.0,127.0,127.0,131.0,130.0,131.0,140.0,169.0,168.0,165.0,...,143.0,145.0,147.0,147.0,149.0,150.0,151.0,152.0,150.0,0

In [269]:
# Reference: https://towardsdatascience.com/a-quick-overview-of-5-scikit-learn-classification-algorithms-33fdc11ab0b9
# Divide data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(merged_data.drop('label', axis=1), merged_data.label ,test_size = 0.2, random_state=13)

# Logistic regression - train the model and then predict() function to make predictions on the test set
from sklearn.linear_model import LogisticRegression
clf_win = LogisticRegression().fit(x_train, y_train)
predictions_logistic = clf_win.predict(x_test)

# Run classification report to compare predictions (shows accuracy of 0.8)
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions_logistic))

/Users/kinlay/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

              precision    recall  f1-score   support

           0       0.83      0.92      0.87       227
           1       0.71      0.52      0.60        89

    accuracy                           0.80       316
   macro avg       0.77      0.72      0.73       316
weighted avg       0.79      0.80      0.79       316

In [270]:
# KNN - try KNN and run classification report to compare prediction (accuracy of 0.74)
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier()
neigh.fit(x_train, y_train)
predictions = neigh.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.80      0.86      0.83       227
           1       0.55      0.44      0.49        89

    accuracy                           0.74       316
   macro avg       0.67      0.65      0.66       316
weighted avg       0.73      0.74      0.73       316

In [271]:
# Decision Tree - run classification report to compare prediction 
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
clf.fit(x_train, y_train)
predictions = clf.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.81      0.82      0.82       227
           1       0.53      0.51      0.52        89

    accuracy                           0.73       316
   macro avg       0.67      0.66      0.67       316
weighted avg       0.73      0.73      0.73       316

In [272]:
# Random Forrest - run classification report to compare prediction 
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
clf.fit(x_train, y_train)
predictions = clf.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

/Users/kinlay/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

              precision    recall  f1-score   support

           0       0.84      0.87      0.86       227
           1       0.64      0.57      0.60        89

    accuracy                           0.79       316
   macro avg       0.74      0.72      0.73       316
weighted avg       0.78      0.79      0.78       316

In [273]:
# Gradient boosting - run classification report to compare prediction 
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(random_state=0)
clf.fit(x_train, y_train)
predictions = clf.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.84      0.87      0.85       227
           1       0.63      0.57      0.60        89

    accuracy                           0.78       316
   macro avg       0.73      0.72      0.73       316
weighted avg       0.78      0.78      0.78       316

In [274]:
display(predictions_logistic)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1])

In [275]:
# Reference: https://machinelearningmastery.com/save-load-machine-learning-models-python-scikit-learn/
# Choose the best model and save with pickle
# I choose Logistic regression because it gives the highest accuracy while not being overfitting (1.0)
filename = 'finalized_model.sav'
pickle.dump(clf_win, open(filename, 'wb'))

In [276]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(x_test, y_test)
print(result)

0.8037974683544303

In [277]:
# merged_data.to_csv('testing.csv', header=False, index=False)